# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-03 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180722_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=155),
        ),
    ]
