# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-16 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(default=0, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
