# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180916_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.BooleanField(default=False, verbose_name='Is a comment?'),
        ),
    ]
